---
title: "20523239-Gabriel WS Integration-18"
author: "Gabriel Imam Andaru"
date: "6/10/2021"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
library(Ryacas)
```


1.Evaluate the following definite integrals using R:

$a.)\int_{-1}^{2}(1-5x^4)dx$

```{r}
#a
integrate(function(x){1-5*x^4},-1,2)
```

$b.)\int_{-1}^{1}(x^4-3x^2+5)dx$

```{r}
#b
integrate(function(x){x^4-(3*x^2)+5},-1,1)
```

$c.)\int_{1}^{3}(\frac{x^2+1}{\sqrt{x}})dx$

```{r}
#c
integrate(function(x){(x^2+1)/(x^0.5)},1,3)
```

$d.)\int_{0}^{2}x(2-3x)^2dx$

```{r}
#d
integrate(function(x){x*((2-3*x)^2)},0,2)
```

$e.)\int_{-\pi}^{\pi}(sin(x).cos(x))dx$

```{r}
#e
integrate(function(x) {sin(x)*cos(x)},-pi,pi)
```

$f.)\int_{0}^{5}(e^{x^2+1}.x)dx$

```{r}
#f
integrate(function(x) {exp(x^2+1)*x},0,5)
```


***

2.Perform the following integration using R:

$a.)\int{4x^5}$

```{r}
#a
yac_expr("Integrate(x) 4*x^5")
```

$b.)\int{x^7-3x+2}dx$
```{r}
#b
yac_expr("Integrate(x) x^7-3*x+2")
```

$c.)\int{(x^2-5x+1)(2-3x)dx}$
```{r}
#c
yac_expr("Integrate(x) (x^2+5*x+1)*(2-3*x)")
```

$d.)\int{sin(x).cos(x)dx}$

```{r}
#d
yac_expr("Integrate(x) Sin(x)*Cos(x)")
```

$e.)\int{sin(2x+1)+3cos(3x+5)+ln(x+5)dx}$

```{r}
#e
yac_expr("Integrate(x) Sin(2*x+1)+3*Cos(3*x+5)+Ln(x+5)")
```




